"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: std_msgs.msg

"""

from ._String import Text
from ._Text import Text
__all__ = ["Text", "Text", ]
